### ISSUE TITLE
Support for SLF4J 2.0

### ISSUE THREAD

**Issue by karstenspang** [Mahoney/slf4j-test#32]
It would be beneficial if we can continue using slf4j test, even when we migrate to SLF4J 2.0.x.

I am aware that this is a major undertaking, and it appears that you no longer actively maintain slf4j-test. I would like to volunteer for that work, either in this project, or I could fork the project to my own user and continue the work from there. In any case, the goal would be to produce a version 2 of slf4j-test that works with SLF4J 2.0.x.

**Comment by karstenspang** [comment]
I have forked and started the work.

**Comment by valfirst** [comment]
@karstenspang here is a fork with SLF4J 2.0 support: https://github.com/valfirst/slf4j-test

**Comment by karstenspang** [comment]
Thanks, closing this issue.
